# usage
# docker-compose -f docker-compose.db.yml  up
version: '3.8'
services:
    mongo:
        image: mongo
        hostname: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: gallery-db
    mongo-express:
        depends_on:
            - mongo
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
