version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:4000
        depends_on:
            - mongo
    mongo:
        image: mongo
        hostname: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE:  gallery-db
    mongo-express:
        depends_on:
            - mongo
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
